#!/bin/bash
# RSSHub Railway 部署助手

echo "================================"
echo "RSSHub Railway 部署指南"
echo "================================"
echo ""
echo "📋 准备工作："
echo ""
echo "1. 注册 GitHub 账号（如果没有）"
echo "   访问：https://github.com/signup"
echo ""
echo "2. Fork RSSHub 仓库"
echo "   访问：https://github.com/DIYgod/RSSHub"
echo "   点击右上角 'Fork' 按钮"
echo ""
echo "3. 注册 Railway 账号"
echo "   访问：https://railway.app"
echo "   点击 'Start a New Project'"
echo "   选择 'Login with GitHub'"
echo ""
echo "================================"
echo ""
echo "🚀 部署步骤："
echo ""
echo "1. 在 Railway 点击 '+ New Project'"
echo ""
echo "2. 选择 'Deploy from GitHub repo'"
echo ""
echo "3. 选择你 Fork 的 'RSSHub' 仓库"
echo ""
echo "4. 等待 2-3 分钟，部署完成"
echo ""
echo "5. 获取访问地址："
echo "   - 点击项目 → Settings → Domains"
echo "   - 点击 'Generate Domain'"
echo "   - 复制生成的域名（如：https://xxx.railway.app）"
echo ""
echo "================================"
echo ""
echo "✅ 部署完成后："
echo ""
echo "测试 RSSHub："
echo "  curl https://你的域名.railway.app"
echo ""
echo "测试雪球路由："
echo "  curl https://你的域名.railway.app/xueqiu/user/1247297532"
echo ""
echo "================================"
