#!/bin/bash
# GitHub 快速登录脚本

echo "================================"
echo "GitHub 登录步骤"
echo "================================"
echo ""
echo "方式一：浏览器登录（推荐）"
echo ""
echo "1. 在终端运行："
echo "   gh auth login"
echo ""
echo "2. 选择："
echo "   ? What account do you want to log into? GitHub.com"
echo "   ? What is your preferred protocol for Git operations? HTTPS"
echo "   ? Authenticate Git with your GitHub credentials? Yes"
echo "   ? How would you like to authenticate GitHub CLI? Login with a web browser"
echo ""
echo "3. 复制显示的一次性代码（如：XXXX-XXXX）"
echo ""
echo "4. 按 Enter 打开浏览器"
echo ""
echo "5. 在浏览器中粘贴代码并授权"
echo ""
echo "================================"
echo ""
echo "方式二：Personal Access Token"
echo ""
echo "1. 访问：https://github.com/settings/tokens"
echo ""
echo "2. 点击 'Generate new token (classic)'"
echo ""
echo "3. 勾选权限："
echo "   ✓ repo"
echo "   ✓ read:org"
echo "   ✓ gist"
echo ""
echo "4. 点击 'Generate token'"
echo ""
echo "5. 复制生成的 token（只显示一次）"
echo ""
echo "6. 运行："
echo "   echo '你的token' | gh auth login --with-token"
echo ""
echo "================================"
