#!/bin/bash
# Docker Desktop 安装指南

echo "================================"
echo "Docker Desktop 安装指南"
echo "================================"
echo ""
echo "方式一：官网下载（推荐）"
echo ""
echo "1. 访问官网："
echo "   https://www.docker.com/products/docker-desktop"
echo ""
echo "2. 下载 'Docker Desktop for Mac (Apple Silicon)'"
echo ""
echo "3. 双击安装，拖到 Applications"
echo ""
echo "4. 打开 Docker Desktop，等待启动"
echo ""
echo "================================"
echo ""
echo "方式二：Homebrew 安装（更快）"
echo ""
echo "运行命令："
echo "  brew install --cask docker"
echo ""
echo "然后打开 Docker Desktop 应用"
echo ""
echo "================================"
echo ""
echo "安装完成后验证："
echo "  docker --version"
echo "  docker run hello-world"
echo ""
echo "================================"
