#!/bin/bash
# Docker Desktop 安装 - 解决网络问题

echo "================================"
echo "Docker Desktop 安装 - 替代方案"
echo "================================"
echo ""
echo "❌ Homebrew 下载失败（网络问题）"
echo ""
echo "================================"
echo ""
echo "方案一：官网手动下载（推荐）"
echo ""
echo "1. 访问官网（可能需要科学上网）："
echo "   https://www.docker.com/products/docker-desktop"
echo ""
echo "2. 或直接下载链接："
echo "   https://desktop.docker.com/mac/main/arm64/Docker.dmg"
echo ""
echo "3. 下载完成后双击安装"
echo ""
echo "================================"
echo ""
echo "方案二：国内镜像下载"
echo ""
echo "阿里云镜像："
echo "   https://mirrors.aliyun.com/docker-toolbox/mac/docker-desktop/"
echo ""
echo "清华大学镜像："
echo "   https://mirrors.tuna.tsinghua.edu.cn/docker-ce/mac/docker-desktop/"
echo ""
echo "================================"
echo ""
echo "方案三：回到云部署（最简单）"
echo ""
echo "点击链接一键部署到 Vercel："
echo "https://vercel.com/new/clone?repository-url=https://github.com/nonlinearHuman/rsshub"
echo ""
echo "================================"
